### ISSUE TITLE
Add support for '3bd218008131fe58c90316' token

### ISSUE THREAD

**Issue by gatzec** [PeculiarVentures/fortify-releases#13]
Reader name: Gemalto USB Shell Token V2 (37AED46F) 00 00
ATR: 3BD218008131FE58C90316

```js
{
   "cards": [{
   	"atr": "3BD218008131FE58C90316",
   	"name": "Token name",
   	"driver": "9997BC25EC2540D916AA47755629CD927C42013B"
   }],
   "drivers": [{
   	"id": "9997BC25EC2540D916AA47755629CD927C42013B",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BD218008131FE58C90316](https://smartcard-atr.apdu.fr/parse?ATR=3BD218008131FE58C90316)

**Comment by gatzec** [comment]
Any chance of adding support for this card?

**Comment by Kharya1337** [comment]
Thank you for reaching out and for your patience in waiting for a response. Apologies for the delay.  

Based on the provided details, we’d like to gather additional information to better understand and address the issue with your smart card. Specifically, could you please clarify the following?  

1. Who manufactures the card (e.g., Gemalto, Thales, etc.)?  
2. What middleware is being used with the card (if any)?  
3. What is the name and path of the PKCS#11 library included with that middleware?  

With this information, we will do our best to identify the source of the issue and ensure compatibility with your card.  

Thank you again for your cooperation!

**Comment by gatzec** [comment]
Hi,
I don't know if such answers will be satisfactory:

1. "Gemalto USB Shell Token V2 (37AED46F) 00 00"
2. Fortify / Setasign
3. `Error: /usr/bin/opensc-pkcs11.so: cannot open shared object file: No such file or directory\n    at PKCS11.load (/snapshot/fortify-app/node_modules/pkcs11js/index.js:275:11)\n    at Module.load (/snapshot/fortify-app/node_modules/graphene-pk11/build/cjs/module.js:12:13)\n    at new OpenSC (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:1859:50)\n    at CardWatcher.getCardObject (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:2123:32)\n    at PCSCWatcher.<anonymous> (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:2060:35)\n    at PCSCWatcher.emit (node:events:513:28)\n    at PCSCWatcher.emit (/snapshot/fortify-app/node_modules/@webcrypto-local/core/build/index.js:25:22)\n    at PCSCWatcher.emit (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:2022:22)\n    at Timeout._onTimeout (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:1981:38)\n    at listOnTimeout (node:internal/timers:569:17)`

**Comment by gatzec** [comment]
Regarding point 2, I also use setasign software.

**Comment by Kharya1337** [comment]
Thank you for providing additional details.

Based on the information you’ve shared, it seems the issue is related to the inability to locate the PKCS#11 library (`/usr/bin/opensc-pkcs11.so`). This typically occurs when the middleware library is either missing or incorrectly configured.  

### Steps to Troubleshoot:  

1. **Check PKCS#11 Library Path**:  
   Confirm that the library path `/usr/bin/opensc-pkcs11.so` exists. On some systems, the correct path might differ (e.g., `/usr/lib/opensc-pkcs11.so`). You can locate it with:  
   ```bash  
   find /usr -name opensc-pkcs11.so  
   ```  
   Update the configuration to use the correct path if needed.  

2. **Test Middleware Functionality**:  
   Use the `pkcs11-tool` command-line utility to confirm the middleware is functional. Example:  
   ```bash  
   pkcs11-tool --module /path/to/opensc-pkcs11.so --list-slots  
   ```  

### Additional Questions:  
To better assist you, could you please provide the following details?  
- **Fortify Version**: Which version of Fortify are you using?  
- **Card Configuration**: What version of the `~/.fortify/card.json` file are you using?  
- **Logs File**: Could you share the logs file for this issue? This will help us identify any additional context or specific errors.

**Comment by gatzec** [comment]
Thank you very much for the tips. The problem is indeed in the location of the `/usr/bin/opensc-pkcs11.so` library.

### 1. Check PKCS#11 Library Path:

`gacek@dell-g15:~$ find /usr -name opensc-pkcs11.so`
`/usr/share/cert_utils/opensc-pkcs11.so`
`/usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so`
`/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so`

### 2. Middleware Functionality

`gacek@dell-g15:~$ pkcs11-tool --module /usr/share/cert_utils/opensc-pkcs11.so --list-slots`
`Available slots:`
`Slot 0 (0x0): Gemalto USB Shell Token V2 (37AED46F) 00 00`
`  token label        : CardOS V5.3 | EC0052954`
`  token manufacturer : Atos IT Solutions and Service...`
`  token model        : PKCS#15 emulated`
`  token flags        : login required, token initialized, PIN initialized`
`  hardware version   : 0.0`
`  firmware version   : 0.0`
`  serial num         : 31`
`  pin min/max        : 4/16`

### 3. Additional Questions:
**Fortify Version**: v2.0.3 (4.11.2024)
**Card Configuration**: `"version": "1.1.20"`,

I tried adding the appropriate entry to the file but without much result.

Card section: 
`  "cards": [`
`    {`
`      "atr": "3BD218008131FE58C90316",`
`      "name": "Gemalto USB Shell Token V2 (37AED46F) 00 00",`
`      "driver": "9997BC25EC2540D916AA47755629CD927C42013B"`
`    },`
`   ...`

Drivers section:
`  "drivers": [`
`    {`
`      "id": "9997BC25EC2540D916AA47755629CD927C42013B",`
`      "name": "CardOS V5.3 | EC0052954",`
`      "file": {`
`        "linux" : "/usr/share/cert_utils/opensc-pkcs11.so"`
`      }`
`    },`
`   ...`

And this is my current log output:

```
{"level":"info","message":"Starting","source":"application","time":1743854920317,"version":"2.1.0"}
{"arch":"x86_64","cpus":20,"freemem":665251840,"level":"info","message":"System info","platform":"Ubuntu","source":"system","totalmem":16436645888,"version":"22.04"}
{"height":1080,"level":"info","message":"Screen size","source":"system","width":1920}
{"dir":"/home/gacek/.mozilla/firefox","level":"info","message":"Firefox profiles directory does not exist","source":"firefox-providers"}
{"level":"info","message":"No Firefox profiles found","source":"firefox-providers"}
{"level":"info","message":"Check for new update","source":"update"}
{"level":"info","message":"Get certificate status","source":"ssl-service","status":"valid"}
{"level":"info","message":"Profiles folder does not exist","path":"/home/gacek/.mozilla/firefox","source":"firefox"}
{"level":"info","message":"SSL certificate is loaded","source":"server"}
{"level":"info","message":"Comparing current version of card.json file with remote","source":"server"}
{"level":"info","message":"New version wasn't found","source":"update"}
{"level":"info","message":"card.json has the latest version","source":"server","version":"1.1.20"}
{"address":"127.0.0.1:31337","level":"info","message":"Started","source":"server"}
{"level":"info","message":"Start PCSC listening","source":"pcsc"}
{"level":"info","message":"PCSC connected successfully","source":"pcsc"}
{"level":"info","message":"Initialize new reader","reader":"Gemalto USB Shell Token V2 (37AED46F) 00 00","source":"pcsc"}
{"atr":"3bd218008131fe58c90316","level":"info","message":"New token was added to the reader","reader":"Gemalto USB Shell Token V2 (37AED46F) 00 00","source":"pcsc"}
{"error":"/usr/bin/opensc-pkcs11.so: cannot open shared object file: No such file or directory","level":"error","message":"Server event error","source":"server","stack":"Error: /usr/bin/opensc-pkcs11.so: cannot open shared object file: No such file or directory\n    at PKCS11.load (/snapshot/fortify-app/node_modules/pkcs11js/index.js:275:11)\n    at Module.load (/snapshot/fortify-app/node_modules/graphene-pk11/build/cjs/module.js:12:13)\n    at new OpenSC (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:1859:50)\n    at CardWatcher.getCardObject (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:2123:32)\n    at PCSCWatcher.<anonymous> (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:2060:35)\n    at PCSCWatcher.emit (node:events:513:28)\n    at PCSCWatcher.emit (/snapshot/fortify-app/node_modules/@webcrypto-local/core/build/index.js:25:22)\n    at PCSCWatcher.emit (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:2022:22)\n    at Timeout._onTimeout (/snapshot/fortify-app/node_modules/@webcrypto-local/server/build/index.js:1981:38)\n    at listOnTimeout (node:internal/timers:569:17)"}
{"atr":"3bd218008131fe58c90316","level":"info","message":"Token was added to the reader","name":"Gemalto USB Shell Token V2 (37AED46F) 00 00","reader":"Gemalto USB Shell Token V2 (37AED46F) 00 00","source":"provider"}
{"level":"info","library":"/usr/share/cert_utils/opensc-pkcs11.so","message":"Loading PKCS#11 library","source":"provider"}
{"level":"info","message":"Looking for slot","slots":1,"source":"provider"}
{"level":"info","message":"Use ConfigTemplateBuilder","source":"provider"}
{"cryptokiVersion":{"major":2,"minor":20},"firmwareVersion":{"major":0,"minor":0},"level":"info","library":"/usr/share/cert_utils/opensc-pkcs11.so","libraryVersion":{"major":0,"minor":20},"manufacturerId":"OpenSC Project","message":"PKCS#11 library information","source":"provider"}
{"level":"info","library":"/usr/share/cert_utils/opensc-pkcs11.so","message":"Crypto provider was added to the list","name":"Gemalto USB Shell Token V2 (37AED46F) 00 00","reader":"Gemalto USB Shell Token V2 (37AED46F) 00 00","source":"provider"}
{"added":1,"level":"info","message":"Amount of tokens was changed","removed":0,"source":"provider-service"}
```

**Comment by gatzec** [comment]
If I make a symbolic link, everything starts working:

```
gacek@dell-g15:~$ sudo ln -s /usr/share/cert_utils/opensc-pkcs11.so /usr/bin/opensc-pkcs11.so
gacek@dell-g15:~$ sudo ln -s /usr/share/cert_utils/libopensc.so.6 /usr/bin/libopensc.so.6
```
Log output:

```
{"level":"info","message":"Starting","source":"application","time":1743856505642,"version":"2.1.0"}
{"arch":"x86_64","cpus":20,"freemem":1017745408,"level":"info","message":"System info","platform":"Ubuntu","source":"system","totalmem":16436645888,"version":"22.04"}
{"height":1080,"level":"info","message":"Screen size","source":"system","width":1920}
{"dir":"/home/gacek/.mozilla/firefox","level":"info","message":"Firefox profiles directory does not exist","source":"firefox-providers"}
{"level":"info","message":"No Firefox profiles found","source":"firefox-providers"}
{"level":"info","message":"Check for new update","source":"update"}
{"level":"info","message":"Get certificate status","source":"ssl-service","status":"valid"}
{"level":"info","message":"Profiles folder does not exist","path":"/home/gacek/.mozilla/firefox","source":"firefox"}
{"level":"info","message":"SSL certificate is loaded","source":"server"}
{"level":"info","message":"Comparing current version of card.json file with remote","source":"server"}
{"level":"info","message":"New version wasn't found","source":"update"}
{"level":"info","message":"card.json has the latest version","source":"server","version":"1.1.20"}
{"address":"127.0.0.1:31337","level":"info","message":"Started","source":"server"}
{"level":"info","message":"Start PCSC listening","source":"pcsc"}
{"level":"info","message":"PCSC connected successfully","source":"pcsc"}
{"level":"info","message":"Initialize new reader","reader":"Gemalto USB Shell Token V2 (37AED46F) 00 00","source":"pcsc"}
{"atr":"3bd218008131fe58c90316","level":"info","message":"New token was added to the reader","reader":"Gemalto USB Shell Token V2 (37AED46F) 00 00","source":"pcsc"}
{"atr":"3bd218008131fe58c90316","level":"info","message":"Token was added to the reader","name":"Gemalto USB Shell Token V2 (37AED46F) 00 00","reader":"Gemalto USB Shell Token V2 (37AED46F) 00 00","source":"provider"}
{"level":"info","library":"/usr/share/cert_utils/opensc-pkcs11.so","message":"Loading PKCS#11 library","source":"provider"}
{"level":"info","message":"Looking for slot","slots":1,"source":"provider"}
{"level":"info","message":"Use ConfigTemplateBuilder","source":"provider"}
{"cryptokiVersion":{"major":2,"minor":20},"firmwareVersion":{"major":0,"minor":0},"level":"info","library":"/usr/share/cert_utils/opensc-pkcs11.so","libraryVersion":{"major":0,"minor":20},"manufacturerId":"OpenSC Project","message":"PKCS#11 library information","source":"provider"}
{"level":"info","library":"/usr/share/cert_utils/opensc-pkcs11.so","message":"Crypto provider was added to the list","name":"Gemalto USB Shell Token V2 (37AED46F) 00 00","reader":"Gemalto USB Shell Token V2 (37AED46F) 00 00","source":"provider"}
{"added":1,"level":"info","message":"Amount of tokens was changed","removed":0,"source":"provider-service"}
```

**Comment by Kharya1337** [comment]
Thanks for clear answers for the additional questions and for sharing the workaround you found!

You're absolutely right — the problem is caused by Fortify looking for PKCS#11 libraries in `/usr/bin/`, while the actual files are currently being installed under `/usr/share/cert_utils/`. This mismatch is a configuration oversight on our part.

We’ll address this properly in the next release by ensuring the correct paths are used internally.

In the meantime, we’ll also include a change to the `card.json` file, so smart cards can be recognized without requiring manual symlinks.

Really appreciate you taking the time to investigate and help improve the project!

**Comment by gatzec** [comment]
It was my pleasure. I'm glad we were able to resolve the issue.
